#if !canImport(ObjectiveC)
import XCTest

extension CommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandTests = [
        ("testDeprecatedFlag", testDeprecatedFlag),
        ("testFlag", testFlag),
        ("testHelp", testHelp),
        ("testShortFlag", testShortFlag),
        ("testShortFlagNeedsToMatchExactly", testShortFlagNeedsToMatchExactly),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommandTests.__allTests__CommandTests),
    ]
}
#endif
