#if !canImport(ObjectiveC)
import XCTest

extension CommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandTests = [
        ("testDeprecatedFlag", testDeprecatedFlag),
        ("testDynamicAccess", testDynamicAccess),
        ("testFlag", testFlag),
        ("testHelp", testHelp),
        ("testShortFlag", testShortFlag),
        ("testShortFlagNeedsToMatchExactly", testShortFlagNeedsToMatchExactly),
    ]
}

extension ConsoleLoggerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConsoleLoggerTests = [
        ("testLoggingLevels", testLoggingLevels),
        ("testLogHandlerCheck", testLogHandlerCheck),
    ]
}

extension ConsoleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConsoleTests = [
        ("testAsk", testAsk),
        ("testConfirm", testConfirm),
        ("testCustomIndicator", testCustomIndicator),
        ("testEphemeral", testEphemeral),
        ("testLoading", testLoading),
        ("testProgress", testProgress),
    ]
}

extension TerminalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TerminalTests = [
        ("testStylizeAllAttrs", testStylizeAllAttrs),
        ("testStylizeBackground", testStylizeBackground),
        ("testStylizeBold", testStylizeBold),
        ("testStylizeForeground", testStylizeForeground),
        ("testStylizeOnlyBold", testStylizeOnlyBold),
        ("testStylizePaletteColor", testStylizePaletteColor),
        ("testStylizePlain", testStylizePlain),
        ("testStylizeRGBColor", testStylizeRGBColor),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommandTests.__allTests__CommandTests),
        testCase(ConsoleLoggerTests.__allTests__ConsoleLoggerTests),
        testCase(ConsoleTests.__allTests__ConsoleTests),
        testCase(TerminalTests.__allTests__TerminalTests),
    ]
}
#endif
