name: deploy-api-docs
on:
  push:
    branches:
      - main
      - v4
permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    uses: vapor/api-docs/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      package: console-kit
      ref: ${{ github.ref_name }}
