name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ main ] }

jobs: 
  unit-tests:
    permissions:
      contents: read
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    with:
      # with_windows: true
      with_musl: true
      # with_android: true
      with_linting: true
    secrets: inherit
    
  package-traits:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container: swift:noble
    steps:
      - name: Check out ConsoleKit
        uses: actions/checkout@v6
      - name: Run tests with traits disabled
        run: swift test --disable-default-traits

  submit-dependencies:
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' }}
    uses: vapor/ci/.github/workflows/submit-deps.yml@main
    secrets: inherit

  # integration-check:
  #   runs-on: ubuntu-latest
  #   container: swift:noble
  #   steps:
  #     - uses: actions/checkout@v6
  #       with: { path: console-kit }
  #     - uses: actions/checkout@v6
  #       with: { repository: 'vapor/vapor', path: vapor }
  #     - run: swift package --package-path vapor edit console-kit --path console-kit
  #     - run: swift test --package-path vapor